branches:
  only:
  - master
language: python
python:
  - "3.8"
# # command to install dependencies
install:
  - pip install codecov
  - pip install .
  - pytraction_get_data
script:
  - python setup.py test
after_success:
  - codecov -t $CODECOV_TOKEN