version: "3.3"

services:
    deep-glass:
        image: 'pytraction:lastest'
        build:
            context: ./
            dockerfile: docker/Dockerfile
        volumes: 
            - ./:/pytraction
        command: tail -f /dev/null
