
piv:
  min_window_size: null
  overlap_ratio: 0.5 
  coarse_factor: 0 
  dt: 1
  validation_method: mean_velocity
  trust_1st_iter: 0 
  validation_iter: 3 
  tolerance: 1.5 
  nb_iter_max: 1 
  sig2noise_method: peak2peak

tfm: 
  E: null
  s: null
  meshsize: null
  pix_per_mu: null

settings:
  bead_channel: 0
  cell_channel: 1
  segment: False
  device: cpu
  crop_aligned_slice: False
      
    